soc_dashboard_index:
    path:     /
    defaults: { _controller: SOCSocBundle:Default:index }

soc_lineup_index:
    path:     /lineup
    defaults: { _controller: SOCSocBundle:Default:index }

soc_standings_index:
    path:     /standings
    defaults: { _controller: SOCSocBundle:Default:index }

soc_matchday_index:
    path:     /matchday
    defaults: { _controller: SOCSocBundle:Default:index }

SOCSocBundle_player:
    resource: "@SOCSocBundle/Resources/config/routing/player.yml"
    prefix:   /player
