soc_dashboard_index:
    path:     /
    defaults: { _controller: SOCSocBundle:Default:index }

soc_dashboard_news:
    path:     /dashboard/news
    defaults: { _controller: SOCSocBundle:Default:news }

soc_lineup_index:
    path:     /lineup
    defaults: { _controller: SOCSocBundle:Default:lineup }

soc_lineup_print:
    path:     /lineup/{matchday}/print
    defaults: { _controller: SOCSocBundle:Default:lineupPrint }

soc_team_index:
    path:     /team
    defaults: { _controller: SOCSocBundle:Default:team }

soc_lineup_test:
    path:     /test
    defaults: { _controller: SOCSocBundle:Default:test }

soc_standings_index:
    path:     /standings
    defaults: { _controller: SOCSocBundle:Default:index }

soc_score_index:
    path:     /score
    defaults: { _controller: SOCSocBundle:Default:score }

soc_matchday_index:
    path:     /matchday
    defaults: { _controller: SOCSocBundle:Default:index }

soc_player:
    resource: "@SOCSocBundle/Resources/config/routing/player.yml"
    prefix:   /player





