parameters:
#    soc_soc.example.class: SOC\Bundle\SocBundle\Example

services:
#    soc_soc.example:
#        class: %soc_soc.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
