parameters:
#    soc_soc.example.class: SOC\Bundle\SocBundle\Example

services:
    sonata.admin.player:
        class: SOC\Bundle\SocBundle\Admin\PlayerAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Spieler" }
        arguments:
            - ~
            - SOC\Bundle\SocBundle\Entity\Player
            - ~
        calls:
            - [ setTranslationDomain, [SOCSocBundle]]