imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: fos/user.yml }
    - { resource: doctrine/main.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources: ['bootstrap_3_layout.html.twig']

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    #bundles:        [ ]
    #java: /usr/bin/java
    filters:
    filters:
        cssrewrite: ~
        jsqueeze: ~
        scssphp:
            # the formatter must be the FQCN (don't use the 'compressed' value)
            formatter: "Leafo\\ScssPhp\\Formatter\\Compressed"
    assets:
        js_default:
            inputs:
                - bundles/socsoc/js/jquery-2.1.1.js
                - bundles/socsoc/js/bootstrap.js
                - bundles/socsoc/js/plugins/metisMenu/jquery.metisMenu.js
                - bundles/socsoc/js/plugins/slimscroll/jquery.slimscroll.js
                - bundles/socsoc/js/underscore-min.js
            filters:
                - ?jsqueeze

        js_dashboard:
            inputs:
                - bundles/socsoc/js/inspinia.js
                - bundles/socsoc/js/moment-with-locales.js
                - bundles/socsoc/js/jquery.mustache.js
                - bundles/socsoc/js/nprogress.js
                - bundles/socsoc/js/plugins/footable/footable.all.min.js
                - bundles/socsoc/js/plugins/toastr/toastr.min.js
            filters:
                - ?jsqueeze

        css_default:
            inputs:
                - bundles/socsoc/css/bootstrap.css
                - bundles/socsoc/font-awesome/css/font-awesome.css
                - bundles/socsoc/css/animate.css
                - bundles/socsoc/css/style.css
                - bundles/socsoc/css/nprogress.css
                - bundles/socsoc/css/lineup.css
                - bundles/socsoc/css/plugins/toastr/lineup.css
            filters:
                - cssrewrite

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }


sonata_block:
    default_contexts: [cms]
    blocks:
        # Enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts:   [admin]
        # Your other blocks

sonata_admin:
    title:      S.O.C.
    title_logo: bundles/socsoc/img/avatar-klopp.png

parameters:
    soc:
        participants:
            - { name: lutz, avatar: bundles/socsoc/img/avatar-eastwood.png }
            - { name: jens, avatar: bundles/socsoc/img/avatar-klopp.png }
            - { name: torsten, avatar: bundles/socsoc/img/avatar-spok.png }
            - { name: christian, avatar: bundles/socsoc/img/avatar-waits.png }
            - { name: alex, avatar: bundles/socsoc/img/avatar-gibson.png }
        budget: 60000000
        players_needed: 22

