imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources: ['bootstrap_3_layout.html.twig']

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    #bundles:        [ ]
    #java: /usr/bin/java
    filters:
    filters:
        cssrewrite: ~
        jsqueeze: ~
        scssphp:
            # the formatter must be the FQCN (don't use the 'compressed' value)
            formatter: "Leafo\\ScssPhp\\Formatter\\Compressed"
    assets:
        js_default:
            inputs:
                - bundles/socsoc/js/jquery-2.1.1.js
                - bundles/socsoc/js/bootstrap.js
                - bundles/socsoc/js/plugins/metisMenu/jquery.metisMenu.js
                - bundles/socsoc/js/plugins/slimscroll/jquery.slimscroll.js
                - bundles/socsoc/js/underscore-min.js
            filters:
                - ?jsqueeze

        js_dashboard:
            inputs:
                - bundles/socsoc/js/inspinia.js
                - bundles/socsoc/js/moment-with-locales.js
                - bundles/socsoc/js/jquery.mustache.js
                - bundles/socsoc/js/nprogress.js
                - bundles/socsoc/js/plugins/footable/footable.all.min.js
            filters:
                - ?jsqueeze

        css_default:
            inputs:
                - bundles/socsoc/css/bootstrap.css
                - bundles/socsoc/font-awesome/css/font-awesome.css
                - bundles/socsoc/css/animate.css
                - bundles/socsoc/css/style.css
                - bundles/socsoc/css/nprogress.css
            filters:
                - cssrewrite

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: SOC\Bundle\SocBundle\Entity\User

sonata_block:
    default_contexts: [cms]
    blocks:
        # Enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts:   [admin]
        # Your other blocks

sonata_admin:
    title:      S.O.C.
    title_logo: bundles/socsoc/img/avatar-klopp.png
