soc_soc:
    resource: "@SOCSocBundle/Resources/config/routing.yml"
    prefix:   /soc

soc_lutz_index:
    pattern: /lb/{slug}.{_format}
    defaults: { _controller: SOCSocBundle:Default:test }
    requirements:
        _format: html

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#redirecting the root
root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /login
        permanent: true

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin