soc_soc:
    resource: "@SOCSocBundle/Resources/config/routing.yml"
    prefix:   /soc

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#redirecting the root
root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /login
        permanent: true

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

soc_rest:
    resource: "@SOCSocBundle/Resources/config/routing/rest.yml"
    prefix:   /api/rest